/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 16
   Tile set      : C:\users\anon\Desktop\gba_test\gbr\bgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __background_h_INCLUDE
#define __background_h_INCLUDE

#define backgroundWidth 32
#define backgroundHeight 16
#define backgroundBank 0

extern const unsigned char background[];

#endif

/* End of BACKGROUND.H */
